version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: strongPassword
      MYSQL_ROOT_PASSWORD: strongPassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
      - '33060:33060'
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: strongPassword
    ports:
      - '8080:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: